name: tmate-slave
base: core18
confinement: classic

summary: The best tmate-slave snap you can find.
description: |
  tmate-slave, built for you by the Travis CI team.
adopt-info: tmate-slave


apps:
  tmate-slave:
    command: bin/tmate-slave
    adapter: full
    environment:
      LC_ALL: C.UTF-8

parts:
  tmate-slave:
    source: https://github.com/tmate-io/tmate-slave.git
    plugin: autotools
    build-packages:
    - libevent-dev
    - libmsgpack-dev
    - libncurses-dev
    - libtool
    - pkg-config
    - zlib1g-dev
    stage-packages:
    - libevent-2.1-6
    - libmsgpackc2
    override-pull: |
      snapcraftctl pull
      version="$(git describe --always | sed -e 's/-/+git/;y/-/./')"
      # If building from a tag we are on a stable grade, if not devel
      [ -n "$(echo $version | grep "+git")" ] && grade=devel || grade=stable
      snapcraftctl set-version "$version"
      snapcraftctl set-grade "$grade"
    after:
    - libssh
  libssh:
    source: https://git.libssh.org/projects/libssh.git
    source-tag: libssh-0.8.7
    plugin: cmake
    build-packages:
    - libssl-dev
